### ISSUE TITLE
Question about how to convert from a topdown view to a frontal view

### ISSUE THREAD

**Issue by Katsuyuki0007** [ThierryDeruyttere/Talk2Car-Destination#1]
Hi, thanks for your great dataset!
I wanted to try to convert the Ground Truth in the top-down view onto the frontal view, and I referred to [draw_heatmap_frontal_t2c](https://github.com/ThierryDeruyttere/Talk2Car-Destination/blob/cd31a2c249ff6a5b5e1493f6bf81a6f9072babaa/baselines/DistributionPrediction/utils.py#L382), but I could not figure out why the constants(ex. 120, 7, 80, 40) in it have these values.

```
x = x / X.shape[0] * 120 - 7
y = y / X.shape[1] * 80 - 40
```

What are these values based on?

**Comment by ThierryDeruyttere** [comment]
Hi there! 

Thank you for the interest in our dataset! 
In Section 3 (Dataset) from our paper you can find the following sentence:

```
We normalize the sizes of the top-down views such that they correspond to physical map regions of 120 × 80 meters in size, with the ego-car located seven meters (7 meters) from the left boundary and halfway (40 meters) along the height of the top-down view
```

I hope this helps.
