### ISSUE TITLE
Question about "gt_referred_obj_top".

### ISSUE THREAD

**Issue by oli-21** [ThierryDeruyttere/Talk2Car-Destination#2]
Hi.
Thank you for publicizing this great dataset.
I would like to ask you something.

How did you get "gt_referred_obj_top" in the JSON?
Did you generate it by converting "2d_box" or something of the original [Talk2Car](https://github.com/talk2car/Talk2Car/tree/master/data)? If so, could you please share the equation and code to convert?

Sorry if I missed it written somewhere.
Thank you in advance.

**Comment by ThierryDeruyttere** [comment]
Hi,

Thank you for your interest in our dataset!
We converted all ground truth bounding boxes from nuScenes in the Talk2Car scenes to top-down with some of the functionality provided by nuScenes.
I'm attaching the two (un-cleaned) files that we used to get these converted boxes in a zip file.

[extract_gt_boxes_and_top_down.zip](https://github.com/ThierryDeruyttere/Talk2Car-Destination/files/9829921/extract_gt_boxes_and_top_down.zip)

**Comment by oli-21** [comment]
Thank you for your quick reply and sharing the source code. I'll try using it!

**Comment by ThierryDeruyttere** [comment]
Hey no problem! Just letting you know that the code i sent you will 100% not run as-is as you need to install the full talk2car dataset and nuscenes. I just provided the code that we used to project the ground truth bounding boxes for your information.
