### ISSUE TITLE
How the referred object under top down view is obtained? 

### ISSUE THREAD

**Issue by LutaoChu** [ThierryDeruyttere/Talk2Car-Destination#6]
Is it by projecting the box of the referred Object on the image to the top down view? If so, how is the projection done? Especially for off-ground objects which position from 2D to 3D cannot be determined.

**Comment by ThierryDeruyttere** [comment]
Good question! We based the code to project the bounding box to a top-down view on the nuScenes code.

You can find how we project the bounding boxes to top-down in our code here 
https://github.com/ThierryDeruyttere/Talk2Car-Destination/blob/2d6836c3af665131f8d599a0db8f235c42257755/object_detectors/mmdetection3d-master/extract_frontal_top_down_boxes_feats_fcos3d.py#L469-L510

**Comment by ThierryDeruyttere** [comment]
Here is an example of in what that code resulted in.
Red is the ego car.
Green is the gt location of an object
and black is the predicted locations.

![image](https://github.com/ThierryDeruyttere/Talk2Car-Destination/assets/6353651/2089bf69-6964-45f5-af20-c8de37deb679)

**Comment by ThierryDeruyttere** [comment]
[DrawPredictionsTopDown.zip](https://github.com/ThierryDeruyttere/Talk2Car-Destination/files/13363170/DrawPredictionsTopDown.zip)
In this zip you'll find a notebook we used to test projecting the predicted bounding boxes to top-down.
I'm providing this notebook as-is. This is still using the old files we used to have. In this repository I cleaned everything and made things easier.

**Comment by LutaoChu** [comment]
Thank you so much!
I read the code you provided, and I have a question: 2D to 3D requires depth information. Does this information come from the prediction results of FCOS3D? 
I understand that the gravity center here is 3D coordinates, which are converted from image box and depth information, right?

https://github.com/ThierryDeruyttere/Talk2Car-Destination/blob/2d6836c3af665131f8d599a0db8f235c42257755/object_detectors/mmdetection3d-master/extract_frontal_top_down_boxes_feats_fcos3d.py#L229C24-L229C24

**Comment by ThierryDeruyttere** [comment]
Yes you are correct, the 3D information comes from FCOS3D. The FCOS3D model makes 3D bounding box predictions based on the frontal image of the vehicle. You are also correct in your second question.

The transformation we do with the predicted bounding boxes is to go from the image space to some global coordinate system that nuScenes uses and then map these global coordinates to top-down coordinates.

**Comment by LutaoChu** [comment]
I undersatand. Thanks!
